"""Questions « Drapeaux » générées depuis le pack SVG (server/media/flags/).

Catégorie auto : type=flag, auto=1 (l'auto-correction SUGGÈRE à l'hôte, qui
décide). Liste curée de pays reconnaissables, avec noms FR + alternatives
d'orthographe courantes. On n'utilise pas les 255 codes (beaucoup de
territoires obscurs = mauvaises questions).
"""

# code ISO-2 (minuscule, = nom de fichier .svg) -> (nom FR, [alternatives])
_FLAGS: dict[str, tuple[str, list[str]]] = {
    # --- Europe ---
    "fr": ("France", []),
    "de": ("Allemagne", []),
    "es": ("Espagne", []),
    "it": ("Italie", []),
    "gb": ("Royaume-Uni", ["Angleterre", "UK", "Grande-Bretagne"]),
    "pt": ("Portugal", []),
    "be": ("Belgique", []),
    "nl": ("Pays-Bas", ["Hollande"]),
    "ch": ("Suisse", []),
    "at": ("Autriche", []),
    "ie": ("Irlande", []),
    "se": ("Suède", []),
    "no": ("Norvège", []),
    "dk": ("Danemark", []),
    "fi": ("Finlande", []),
    "is": ("Islande", []),
    "pl": ("Pologne", []),
    "cz": ("Tchéquie", ["République tchèque"]),
    "sk": ("Slovaquie", []),
    "hu": ("Hongrie", []),
    "ro": ("Roumanie", []),
    "bg": ("Bulgarie", []),
    "gr": ("Grèce", []),
    "hr": ("Croatie", []),
    "rs": ("Serbie", []),
    "ua": ("Ukraine", []),
    "ru": ("Russie", []),
    "tr": ("Turquie", []),
    "lu": ("Luxembourg", []),
    "mc": ("Monaco", []),
    "al": ("Albanie", []),
    "si": ("Slovénie", []),
    "ee": ("Estonie", []),
    "lv": ("Lettonie", []),
    "lt": ("Lituanie", []),
    "by": ("Biélorussie", []),
    "md": ("Moldavie", []),
    "mt": ("Malte", []),
    "cy": ("Chypre", []),
    "me": ("Monténégro", []),
    "ba": ("Bosnie-Herzégovine", ["Bosnie"]),
    "ad": ("Andorre", []),
    "li": ("Liechtenstein", []),
    # --- Amériques ---
    "us": ("États-Unis", ["USA", "Etats-Unis", "Amérique", "Amerique"]),
    "ca": ("Canada", []),
    "mx": ("Mexique", []),
    "br": ("Brésil", []),
    "ar": ("Argentine", []),
    "cl": ("Chili", []),
    "co": ("Colombie", []),
    "pe": ("Pérou", []),
    "ve": ("Venezuela", []),
    "uy": ("Uruguay", []),
    "py": ("Paraguay", []),
    "bo": ("Bolivie", []),
    "ec": ("Équateur", []),
    "cu": ("Cuba", []),
    "jm": ("Jamaïque", []),
    "ht": ("Haïti", []),
    "do": ("République dominicaine", []),
    "cr": ("Costa Rica", []),
    "pa": ("Panama", []),
    "gt": ("Guatemala", []),
    # --- Asie ---
    "cn": ("Chine", []),
    "jp": ("Japon", []),
    "kr": ("Corée du Sud", ["Corée"]),
    "kp": ("Corée du Nord", []),
    "in": ("Inde", []),
    "id": ("Indonésie", []),
    "th": ("Thaïlande", []),
    "vn": ("Vietnam", []),
    "ph": ("Philippines", []),
    "my": ("Malaisie", []),
    "sg": ("Singapour", []),
    "pk": ("Pakistan", []),
    "bd": ("Bangladesh", []),
    "lk": ("Sri Lanka", []),
    "np": ("Népal", []),
    "af": ("Afghanistan", []),
    "ir": ("Iran", []),
    "iq": ("Irak", []),
    "sa": ("Arabie saoudite", []),
    "ae": ("Émirats arabes unis", ["Emirats"]),
    "il": ("Israël", []),
    "jo": ("Jordanie", []),
    "lb": ("Liban", []),
    "sy": ("Syrie", []),
    "qa": ("Qatar", []),
    "kw": ("Koweït", []),
    "kz": ("Kazakhstan", []),
    "mn": ("Mongolie", []),
    "mm": ("Birmanie", ["Myanmar"]),
    "kh": ("Cambodge", []),
    "ge": ("Géorgie", []),
    "am": ("Arménie", []),
    "az": ("Azerbaïdjan", []),
    # --- Afrique ---
    "ma": ("Maroc", []),
    "dz": ("Algérie", []),
    "tn": ("Tunisie", []),
    "ly": ("Libye", []),
    "eg": ("Égypte", []),
    "sn": ("Sénégal", []),
    "ci": ("Côte d'Ivoire", ["Cote d'Ivoire"]),
    "ml": ("Mali", []),
    "ne": ("Niger", []),
    "ng": ("Nigéria", ["Nigeria"]),
    "gh": ("Ghana", []),
    "cm": ("Cameroun", []),
    "cd": ("République démocratique du Congo", ["RD Congo", "Congo"]),
    "ga": ("Gabon", []),
    "ao": ("Angola", []),
    "za": ("Afrique du Sud", []),
    "ke": ("Kenya", []),
    "et": ("Éthiopie", []),
    "tz": ("Tanzanie", []),
    "ug": ("Ouganda", []),
    "zw": ("Zimbabwe", []),
    "mz": ("Mozambique", []),
    "mg": ("Madagascar", []),
    "zm": ("Zambie", []),
    "bf": ("Burkina Faso", []),
    "td": ("Tchad", []),
    "mr": ("Mauritanie", []),
    "gn": ("Guinée", []),
    "bj": ("Bénin", []),
    "tg": ("Togo", []),
    "rw": ("Rwanda", []),
    "so": ("Somalie", []),
    "sd": ("Soudan", []),
    "na": ("Namibie", []),
    "bw": ("Botswana", []),
    "mu": ("Maurice", ["Île Maurice", "Ile Maurice"]),
    "cv": ("Cap-Vert", []),
    # --- Océanie ---
    "au": ("Australie", []),
    "nz": ("Nouvelle-Zélande", []),
    "fj": ("Fidji", []),
    "pg": ("Papouasie-Nouvelle-Guinée", ["Papouasie"]),
}


def flag_questions() -> list[dict]:
    rows = []
    for code, (name, alts) in _FLAGS.items():
        rows.append({
            "category": "Drapeaux",
            "question": "Quel est ce pays ?",
            "answer": name,
            "type": "flag",
            "auto": 1,
            "media": {"kind": "image", "url": f"/media/flags/{code}.svg"},
            "alt_answers": alts,
        })
    return rows


FLAG_QUESTIONS = flag_questions()
